version: "3.0"
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/dockerfile.c
    tty: true
    cap_add:
    - NET_ADMIN
  client:
    container_name: client
    build:
      context: .
      dockerfile: client/dockerfile
    tty: true
    cap_add:
    - NET_ADMIN
    depends_on:
      - server

